# observability/promtail-config.yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: pr-app-logs
    static_configs:
      - targets: ["localhost"]
        labels:
          job: pr-app
          __path__: /var/log/app/*.log
    pipeline_stages:
      - regex:
          expression: "branch=(?P<branch>[^ ]+)" # extracts branch from log lines if present
      - labels:
          branch:
