name: PR Performance Monitoring
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  monitor-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Start monitoring environment
        run: |
          # No API keys needed - everything runs locally!
          export BRANCH="${{ github.head_ref }}"
          docker-compose up -d
      
      - name: Run tests
        run: |
          # Your performance testing here
          curl http://localhost:8000/health
      
      - name: Post results to PR
        uses: actions/github-script@v7
        with:
          script: |
            # Only needs GitHub token (automatically provided)
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              body: "Performance test completed!"
            });
      
      - name: Cleanup
        if: always()
        run: docker-compose down -v